services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: next-document-app
        restart: unless-stopped
        env_file:
            - .env
        environment:
            NODE_ENV: production
            PORT: 3000
        ports:
            - '${APP_PORT:-3000}:3000'
